"""Generic auracle product backend — auto-generated by compose_product.

Do not hand-edit unless you're willing to take ownership — the next
compose run will overwrite this file.

AURACLE_EMIT_VERSION:iter39 — see compose.py _is_stale_compose for the
short-circuit-bypass marker. Bump when emit_server's contract changes
in a way that requires already-composed product repos to be re-emitted.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from pathlib import Path
from typing import Any

from aiohttp import web

# adapters.py is copied alongside this file at compose time.
try:
    from . import adapters
except ImportError:
    from server import adapters  # type: ignore[no-redef]

log = logging.getLogger("auracle_product")

STATIC_DIR = Path(__file__).resolve().parent.parent
PORT = int(os.environ.get("PORT", "8080"))

ROUTES: list[dict] = [
  {
    "path": "/mock-data.js",
    "method": "GET",
    "kind": "window-mock",
    "leaves": {
      "KPIS.p0_incidents_24h.delta": {
        "adapter": "static_value",
        "args": {
          "value": 0
        }
      },
      "KPIS.p0_incidents_24h.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.incident",
          "hours": 24
        }
      },
      "KPIS.p0_incidents_24h.val": {
        "adapter": "bq_count_by_topic",
        "args": {
          "topic": "factory.incident",
          "hours": 24
        }
      },
      "KPIS.deploys_24h.delta": {
        "adapter": "static_value",
        "args": {
          "value": 0
        }
      },
      "KPIS.deploys_24h.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.deploy",
          "hours": 24
        }
      },
      "KPIS.intents_24h.delta": {
        "adapter": "static_value",
        "args": {
          "value": 0
        }
      },
      "KPIS.intents_24h.spark": {
        "adapter": "bq_topic_sparkline",
        "args": {
          "topic": "factory.tasks",
          "hours": 24
        }
      },
      "KPIS.services_up.delta": {
        "adapter": "static_value",
        "args": {
          "value": 0
        }
      },
      "KPIS.services_up.spark": {
        "adapter": "static_value",
        "args": {
          "value": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      },
      "KPIS.services_up.total": {
        "adapter": "cloudrun_services_count",
        "args": {}
      },
      "KPIS.deploys_24h.val": {
        "adapter": "bq_count_by_topic",
        "args": {
          "topic": "factory.deploy",
          "hours": 24
        }
      },
      "KPIS.intents_24h.val": {
        "adapter": "bq_count_by_topic",
        "args": {
          "topic": "factory.tasks",
          "hours": 24
        }
      },
      "KPIS.services_up.val": {
        "adapter": "cloudrun_services_count",
        "args": {}
      },
      "MEMORY_ENTRIES[]": {
        "adapter": "memory_bank_recall",
        "args": {
          "scope": "",
          "limit": 20
        },
        "shape_map": {
          "id": "memory_id",
          "scope": "scope",
          "content": "content_preview",
          "ts": "last_recalled_at"
        }
      },
      "NEW_SKILLS[].id": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "SEARCH_ITEMS": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "THREADS[].id": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "AGENTS[].id": {
        "adapter": "cloudrun_services_list",
        "args": {},
        "shape_map": {
          "id": "name",
          "name": "name",
          "uri": "uri",
          "status": "terminal_condition_state"
        }
      },
      "INFLIGHT": {
        "adapter": "bq_inflight_steps",
        "args": {
          "limit": 10
        },
        "shape_map": {
          "id": "step_id",
          "skill": "skill",
          "slug": "slug",
          "ts": "dispatched_ts"
        }
      },
      "PROJECTS": {
        "adapter": "project_registry_list",
        "args": {},
        "shape_map": {
          "id": "slug",
          "name": "slug",
          "repo": "repo",
          "url": "url",
          "status": "status",
          "description": "description"
        }
      },
      "TOPICS[]": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "fmtTime": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "EVENTS": {
        "adapter": "bq_recent_events",
        "args": {
          "limit": 50
        },
        "shape_map": {
          "id": "step_id",
          "ts": "ts",
          "topic": "topic",
          "skill": "skill",
          "status": "status",
          "intent_id": "intent_id",
          "payload": "payload_preview"
        }
      },
      "MEMORY": {
        "adapter": "memory_bank_recall",
        "args": {
          "limit": 20
        },
        "shape_map": {
          "id": "memory_id",
          "scope": "scope",
          "content": "content_preview",
          "ts": "last_recalled_at"
        }
      },
      "RETROS": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "SKILLS": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "fmtRel": {
        "adapter": "static_value",
        "args": {
          "value": None
        }
      },
      "CHAT": {
        "adapter": "static_value",
        "args": {
          "value": []
        }
      },
      "NOW": {
        "adapter": "static_value",
        "args": {
          "value": 1716000000000
        }
      }
    },
    "helpers": {
      "makeEvent": "const makeEvent = (i) => {\n    const t = EVT_TEMPLATES[i % EVT_TEMPLATES.length];\n    return {\n      id: 'evt_' + (NOW - i * 1234).toString(36),\n      ts: NOW - i * (12 + (i * 7) % 40) * SEC,\n      topic: t.topic,\n      skill: t.skill,\n      stepId: 'stp_' + (0xb000 + i * 41).toString(16),\n      status: t.status,\n    };\n  }",
      "fmtTime": "const fmtTime = (ts) => {\n    const d = new Date(ts);\n    const hh = String(d.getHours()).padStart(2, '0');\n    const mm = String(d.getMinutes()).padStart(2, '0');\n    const ss = String(d.getSeconds()).padStart(2, '0');\n    return hh + ':' + mm + ':' + ss;\n  }",
      "fmtRel": "const fmtRel = (ts) => {\n    const d = NOW - ts;\n    if (d < 60 * SEC) return Math.max(1, Math.round(d / SEC)) + 's ago';\n    if (d < 60 * MIN) return Math.round(d / MIN) + 'm ago';\n    if (d < 24 * HR)  return Math.round(d / HR) + 'h ago';\n    return Math.round(d / DAY) + 'd ago';\n  }"
    }
  }
]

_MOCK_SHAPE: dict = {}

MOCK_BINDINGS: dict = {
  "path": "/mock-data.js",
  "method": "GET",
  "kind": "window-mock",
  "leaves": {
    "KPIS.p0_incidents_24h.delta": {
      "adapter": "static_value",
      "args": {
        "value": 0
      }
    },
    "KPIS.p0_incidents_24h.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.incident",
        "hours": 24
      }
    },
    "KPIS.p0_incidents_24h.val": {
      "adapter": "bq_count_by_topic",
      "args": {
        "topic": "factory.incident",
        "hours": 24
      }
    },
    "KPIS.deploys_24h.delta": {
      "adapter": "static_value",
      "args": {
        "value": 0
      }
    },
    "KPIS.deploys_24h.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.deploy",
        "hours": 24
      }
    },
    "KPIS.intents_24h.delta": {
      "adapter": "static_value",
      "args": {
        "value": 0
      }
    },
    "KPIS.intents_24h.spark": {
      "adapter": "bq_topic_sparkline",
      "args": {
        "topic": "factory.tasks",
        "hours": 24
      }
    },
    "KPIS.services_up.delta": {
      "adapter": "static_value",
      "args": {
        "value": 0
      }
    },
    "KPIS.services_up.spark": {
      "adapter": "static_value",
      "args": {
        "value": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }
    },
    "KPIS.services_up.total": {
      "adapter": "cloudrun_services_count",
      "args": {}
    },
    "KPIS.deploys_24h.val": {
      "adapter": "bq_count_by_topic",
      "args": {
        "topic": "factory.deploy",
        "hours": 24
      }
    },
    "KPIS.intents_24h.val": {
      "adapter": "bq_count_by_topic",
      "args": {
        "topic": "factory.tasks",
        "hours": 24
      }
    },
    "KPIS.services_up.val": {
      "adapter": "cloudrun_services_count",
      "args": {}
    },
    "MEMORY_ENTRIES[]": {
      "adapter": "memory_bank_recall",
      "args": {
        "scope": "",
        "limit": 20
      },
      "shape_map": {
        "id": "memory_id",
        "scope": "scope",
        "content": "content_preview",
        "ts": "last_recalled_at"
      }
    },
    "NEW_SKILLS[].id": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "SEARCH_ITEMS": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "THREADS[].id": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "AGENTS[].id": {
      "adapter": "cloudrun_services_list",
      "args": {},
      "shape_map": {
        "id": "name",
        "name": "name",
        "uri": "uri",
        "status": "terminal_condition_state"
      }
    },
    "INFLIGHT": {
      "adapter": "bq_inflight_steps",
      "args": {
        "limit": 10
      },
      "shape_map": {
        "id": "step_id",
        "skill": "skill",
        "slug": "slug",
        "ts": "dispatched_ts"
      }
    },
    "PROJECTS": {
      "adapter": "project_registry_list",
      "args": {},
      "shape_map": {
        "id": "slug",
        "name": "slug",
        "repo": "repo",
        "url": "url",
        "status": "status",
        "description": "description"
      }
    },
    "TOPICS[]": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "fmtTime": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "EVENTS": {
      "adapter": "bq_recent_events",
      "args": {
        "limit": 50
      },
      "shape_map": {
        "id": "step_id",
        "ts": "ts",
        "topic": "topic",
        "skill": "skill",
        "status": "status",
        "intent_id": "intent_id",
        "payload": "payload_preview"
      }
    },
    "MEMORY": {
      "adapter": "memory_bank_recall",
      "args": {
        "limit": 20
      },
      "shape_map": {
        "id": "memory_id",
        "scope": "scope",
        "content": "content_preview",
        "ts": "last_recalled_at"
      }
    },
    "RETROS": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "SKILLS": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "fmtRel": {
      "adapter": "static_value",
      "args": {
        "value": None
      }
    },
    "CHAT": {
      "adapter": "static_value",
      "args": {
        "value": []
      }
    },
    "NOW": {
      "adapter": "static_value",
      "args": {
        "value": 1716000000000
      }
    }
  },
  "helpers": {
    "makeEvent": "const makeEvent = (i) => {\n    const t = EVT_TEMPLATES[i % EVT_TEMPLATES.length];\n    return {\n      id: 'evt_' + (NOW - i * 1234).toString(36),\n      ts: NOW - i * (12 + (i * 7) % 40) * SEC,\n      topic: t.topic,\n      skill: t.skill,\n      stepId: 'stp_' + (0xb000 + i * 41).toString(16),\n      status: t.status,\n    };\n  }",
    "fmtTime": "const fmtTime = (ts) => {\n    const d = new Date(ts);\n    const hh = String(d.getHours()).padStart(2, '0');\n    const mm = String(d.getMinutes()).padStart(2, '0');\n    const ss = String(d.getSeconds()).padStart(2, '0');\n    return hh + ':' + mm + ':' + ss;\n  }",
    "fmtRel": "const fmtRel = (ts) => {\n    const d = NOW - ts;\n    if (d < 60 * SEC) return Math.max(1, Math.round(d / SEC)) + 's ago';\n    if (d < 60 * MIN) return Math.round(d / MIN) + 'm ago';\n    if (d < 24 * HR)  return Math.round(d / HR) + 'h ago';\n    return Math.round(d / DAY) + 'd ago';\n  }"
  }
}

_cache: dict = {}
_CACHE_TTL = 30.0


async def _cached(key: str, fn: Any, *args: Any, **kwargs: Any) -> Any:
    now = time.monotonic()
    hit = _cache.get(key)
    if hit and (now - hit[0]) < _CACHE_TTL:
        return hit[1]
    val = await fn(*args, **kwargs)
    _cache[key] = (now, val)
    return val


async def _dispatch(binding: dict) -> Any:
    fn = getattr(adapters, binding["adapter"])
    raw = await fn(**binding.get("args", {}))
    return _apply_shape_map(raw, binding.get("shape_map"))


def _post(value: Any, kind: str | None) -> Any:
    if isinstance(value, Exception):
        return None
    if kind == "to_int":
        try:
            return int(value)
        except (TypeError, ValueError):
            if isinstance(value, list):
                return len(value)
            return 0
    if kind == "to_str":
        try:
            return str(value)
        except Exception:
            return ""
    if kind == "to_list":
        return list(value) if isinstance(value, (list, tuple)) else []
    return value


def _set_leaf(target: dict, path: str, value: Any) -> None:
    """Set target[a][b][c] = value where path == 'a.b.c'. Strips trailing [] from keys."""
    parts = path.split(".")
    cur = target
    for p in parts[:-1]:
        key = p[:-2] if p.endswith("[]") else p
        cur = cur.setdefault(key, {})
    last = parts[-1]
    key = last[:-2] if last.endswith("[]") else last
    cur[key] = value


def _resolve_field(source: Any, expr: str) -> Any:
    """Resolve a shape_map value expression against a source dict.

    Forms:
      "name"            pluck source["name"]
      "a.b.c"           nested pluck source["a"]["b"]["c"]
      "=<json-literal>" literal (parsed as JSON: "='x'", "=42", "=null", "=true")
      "=<bare-string>"  fallback: literal string after the equals sign
    """
    if not isinstance(expr, str):
        return expr
    if expr.startswith("="):
        body = expr[1:]
        try:
            return json.loads(body)
        except (ValueError, TypeError):
            # Accept JS-style single-quoted strings ('active') as a
            # convenience — Gemini emits these often.
            if len(body) >= 2 and body[0] == body[-1] and body[0] in ("'", '"'):
                return body[1:-1]
            return body
    if not isinstance(source, dict):
        return None
    cur: Any = source
    for part in expr.split("."):
        if isinstance(cur, dict):
            cur = cur.get(part)
        else:
            return None
    return cur


def _apply_shape_map(raw: Any, shape_map: dict | None) -> Any:
    """Transform `raw` into the consumer's expected shape.

    If `shape_map` is falsy, return raw unchanged.
    If raw is a list, apply shape_map per item.
    Otherwise treat raw as a single object and apply once.
    """
    if not shape_map or not isinstance(shape_map, dict):
        return raw
    def _one(item: Any) -> dict:
        return {k: _resolve_field(item, v) for k, v in shape_map.items()}
    if isinstance(raw, list):
        return [_one(it) for it in raw]
    return _one(raw)


def _make_handler(binding: dict) -> Any:
    async def _handler(request: web.Request) -> web.Response:
        try:
            data = await _cached(
                f"{binding['path']}:{binding['method']}",
                _dispatch,
                binding,
            )
            return web.json_response(data)
        except Exception as exc:
            log.exception("handler error path=%s: %s", binding["path"], exc)
            return web.json_response({"error": str(exc)}, status=500)
    return _handler


def _make_leaves_handler(binding: dict) -> Any:
    async def _handler(request: web.Request) -> web.Response:
        leaves = binding.get("leaves") or {}
        leaf_keys = list(leaves.keys())
        tasks = []
        for lk in leaf_keys:
            leaf = leaves[lk]
            fn = getattr(adapters, leaf["adapter"])
            tasks.append(fn(**leaf.get("args", {})))
        raw = await asyncio.gather(*tasks, return_exceptions=True)
        out: dict = {}
        for lk, result in zip(leaf_keys, raw):
            leaf = leaves[lk]
            shaped = _apply_shape_map(
                _post(result, leaf.get("postprocess")),
                leaf.get("shape_map"),
            )
            _set_leaf(out, lk, shaped)
        return web.json_response(out)
    return _handler


_MIME = {
    ".jsx": "application/javascript",
    ".js": "application/javascript",
    ".css": "text/css",
    ".html": "text/html",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


async def _build_mock_js() -> web.Response:
    """Serve mock-data.js — original fixture content + a small fetch-bootstrap
    that pulls real data from the per-key /api/<key> endpoints emitted alongside.

    iter-29 architectural shift: mock-data.js stays as the FIXTURE that
    declares the consumer shape. Real data flows through real REST
    endpoints (/api/agents, /api/events, etc.). The bootstrap appended
    here fetches each endpoint and overlays the live values into
    window.MOCK after page load — the React app then re-reads window.MOCK
    on its next render cycle and shows real data. mock-data.js no longer
    contains inline overlay data.

    Falls back to a bare-data IIFE when the original file is absent
    (synthetic frontends with no pre-existing mock-data.js).
    """
    leaves = MOCK_BINDINGS.get("leaves") or {}
    original_path = STATIC_DIR / "mock-data.js"
    if original_path.is_file():
        # Overlay mode: serve original fixtures, then patch bound leaves
        try:
            original_js = original_path.read_text(encoding="utf-8")
        except OSError:
            original_js = ""
        # iter-29: derive the list of top-level keys that have real-data
        # endpoints from the leaves dict. Each unique top-level key gets
        # a /api/<lowercase-key> endpoint emitted in build_app(). The
        # bootstrap fetches each in parallel and overlays window.MOCK.
        top_keys: dict = {}
        for lk in leaves.keys():
            top = lk.split(".")[0].split("[]")[0].rstrip(".")
            if top:
                top_keys[top] = True
        endpoints = sorted(top_keys.keys())
        endpoint_pairs_json = json.dumps([(k, "/api/" + k.lower()) for k in endpoints])
        bootstrap_lines = [
            "(function () {",
            "  /* iter-29 fetch-bootstrap: pulls real data from the",
            "     adapter-backed REST endpoints emitted by the factory and",
            "     overlays the values into window.MOCK so the consumer app",
            "     reads live data on the next render cycle. mock-data.js",
            "     itself stays as the fixture / schema declaration.",
            "     iter-32: only overlay when the endpoint returns a",
            "     meaningful payload — empty arrays, empty objects, null,",
            "     and {id: null} not-found shapes preserve the original",
            "     fixture so unbound keys keep their rich content and the",
            "     UI doesn't crash dereferencing empty arrays. */",
            "  var _ENDPOINTS = " + endpoint_pairs_json + ";",
            "  if (typeof window === 'undefined' || !window.MOCK || !_ENDPOINTS.length) return;",
            "  function _isMeaningful(v) {",
            "    if (v === null || v === undefined) return false;",
            "    if (Array.isArray(v)) return v.length > 0;",
            "    if (typeof v === 'object') {",
            "      var keys = Object.keys(v);",
            "      if (keys.length === 0) return false;",
            "      if (keys.length === 1 && keys[0] === 'id' && v.id === null) return false;",
            "      return true;",
            "    }",
            "    if (typeof v === 'string') return v.length > 0;",
            "    if (typeof v === 'number') return true;",
            "    return true;",
            "  }",
            "  Promise.all(_ENDPOINTS.map(function (pair) {",
            "    var k = pair[0]; var url = pair[1];",
            "    return fetch(url, { cache: 'no-store' })",
            "      .then(function (r) { return r.ok ? r.json() : null; })",
            "      .then(function (val) { if (_isMeaningful(val)) window.MOCK[k] = val; })",
            "      .catch(function () { /* keep fixture on error */ });",
            "  })).then(function () {",
            "    try { document.dispatchEvent(new CustomEvent('auracle-data-loaded')); } catch (e) {}",
            "  });",
            "})();",
        ]
        bootstrap = chr(10).join(bootstrap_lines)
        body = (
            original_js
            + chr(10)
            + "/* ─── auracle real-data bootstrap (iter-29) ─── */"
            + chr(10)
            + bootstrap
        )
        return web.Response(text=body, content_type="application/javascript")

    # Fallback: original mock-data.js missing — emit just the bound data
    # via inline IIFE (the iter-14 dynamic-mock-data path, kept for
    # synthetic frontends that have no fixture file).
    leaf_keys = list(leaves.keys())
    tasks = []
    for lk in leaf_keys:
        leaf = leaves[lk]
        fn = getattr(adapters, leaf["adapter"])
        tasks.append(fn(**leaf.get("args", {})))
    raw = await asyncio.gather(*tasks, return_exceptions=True)
    data: dict = {}
    for lk, result in zip(leaf_keys, raw):
        leaf = leaves[lk]
        _set_leaf(data, lk, _post(result, leaf.get("postprocess")))
    helpers = MOCK_BINDINGS.get("helpers") or {}
    data_json = json.dumps(data)
    helper_items = list(helpers.items())
    helper_block = chr(10).join(src for _, src in helper_items)
    helper_names = ", ".join(name for name, _ in helper_items)
    lines = ["(function () {"]
    if helper_block:
        lines.append("  // ── helpers (verbatim from compose-time extraction) ─────────")
        lines.append(helper_block)
    lines.append("  // ── data (assembled at request time) ──────────────────")
    lines.append("  const _DATA = " + data_json + ";")
    if helper_names:
        lines.append("  window.MOCK = Object.assign({}, _DATA, { " + helper_names + " });")
    else:
        lines.append("  window.MOCK = _DATA;")
    lines.append("})();")
    return web.Response(text=chr(10).join(lines), content_type="application/javascript")


async def _mock_data_js(_: web.Request) -> web.Response:
    return await _cached("mock-data-js", _build_mock_js)


def _make_mock_key_handler(top_key: str) -> Any:
    """Per-top-level-MOCK-key endpoint emitted by iter-29. Calls all
    adapter leaves whose dotted path starts with `top_key` and assembles
    the nested value the frontend's window.MOCK[top_key] would read.

    A whole-array key (AGENTS, EVENTS) usually has ONE binding that
    returns the full array. A nested-dict key (KPIS.services_up.val)
    has many leaves under the same top; each gets its own adapter call
    and the results are merged into a nested dict.
    """
    async def _handler(request: web.Request) -> web.Response:
        leaves = MOCK_BINDINGS.get("leaves") or {}
        matched = {lk: cfg for lk, cfg in leaves.items()
                   if lk == top_key or lk.startswith(top_key + ".") or lk.startswith(top_key + "[]")}
        if not matched:
            return web.json_response(None)
        async def _call(lk: str, cfg: dict) -> Any:
            try:
                fn = getattr(adapters, cfg["adapter"])
                val = await fn(**cfg.get("args", {}))
                val = _post(val, cfg.get("postprocess"))
                return _apply_shape_map(val, cfg.get("shape_map"))
            except Exception as exc:
                log.warning("mock-key %s leaf %s adapter %s failed: %s",
                            top_key, lk, cfg.get("adapter"), exc)
                return None
        keys = list(matched.keys())
        results = await asyncio.gather(*[_call(k, matched[k]) for k in keys])
        # If only one leaf and it IS the top key, return raw
        if len(keys) == 1 and keys[0] == top_key:
            return web.json_response(results[0])
        # iter-39 fix: when leaves are array-shape (TOPKEY[].field), zip
        # them into [{field1: arr1[i], field2: arr2[i], ...}, ...]
        # instead of the broken nested-dict assembly that produced
        # {"": {"id": [...]}}. Triggered whenever any matched leaf
        # path contains "[]" — those are per-field array projections
        # of the same parent list and must reassemble PER-ITEM.
        array_keys = [k for k in keys if "[]" in k]
        if array_keys and len(array_keys) == len(keys):
            # Pure array-shape — collect field names + each list, zip.
            fields: list[tuple[str, list]] = []
            for lk, val in zip(keys, results):
                if not isinstance(val, list):
                    continue
                rel = lk[len(top_key):].lstrip(".")
                field_name = rel.replace("[]", "").lstrip(".") or "value"
                fields.append((field_name, val))
            if not fields:
                return web.json_response([])
            n = min(len(arr) for _, arr in fields)
            items = []
            for i in range(n):
                row: dict = {}
                for fname, arr in fields:
                    elem = arr[i]
                    # If the leaf value is itself a dict, spread it.
                    if isinstance(elem, dict) and fname == "value":
                        row.update(elem)
                    else:
                        row[fname] = elem
                items.append(row)
            return web.json_response(items)
        # Otherwise assemble the nested shape under the top key
        out: dict = {}
        for lk, val in zip(keys, results):
            if val is None:
                continue
            if isinstance(val, (dict, list)) and not val:
                continue
            rel = lk[len(top_key):].lstrip(".")
            if not rel:
                # leaf path is exactly top_key (rare in nested mode)
                out["_top"] = val
                continue
            _set_leaf(out, rel, val)
        return web.json_response(out)
    return _handler


async def static_h(request: web.Request) -> web.Response:
    rel = request.match_info.get("path", "").lstrip("/")
    if not rel:
        rel = "index.html"
    target = (STATIC_DIR / rel).resolve()
    try:
        target.relative_to(STATIC_DIR)
    except ValueError:
        return web.Response(status=404)
    if not target.exists() or not target.is_file():
        target = STATIC_DIR / "index.html"
    return web.FileResponse(target, headers={
        "Content-Type": _MIME.get(target.suffix.lower(), "application/octet-stream")
    })


async def health(_: web.Request) -> web.Response:
    return web.Response(text="ok")


async def journeys_h(_: web.Request) -> web.Response:
    journeys_path = Path(__file__).resolve().parents[2] / "journeys.json"
    if journeys_path.exists():
        try:
            return web.json_response(json.loads(journeys_path.read_text(encoding="utf-8")))
        except Exception:
            pass
    return web.json_response([])


async def _self_ping() -> None:
    import aiohttp as _ah
    url = f"http://127.0.0.1:{PORT}/health"
    async with _ah.ClientSession() as sess:
        while True:
            try:
                async with sess.get(url, timeout=_ah.ClientTimeout(total=5)) as r:
                    await r.text()
            except Exception:
                pass
            await asyncio.sleep(30.0)


def build_app() -> web.Application:
    app = web.Application()
    app.router.add_get("/health", health)
    app.router.add_get("/journeys.json", journeys_h)
    # no API routes
    # iter-29 per-top-level-key endpoints (e.g. /api/agents, /api/events).
    # One per unique top-level MOCK key inferred from leaf bindings.
    _seen_top: set = set()
    for _lk in (MOCK_BINDINGS.get("leaves") or {}).keys():
        _top = _lk.split(".")[0].split("[]")[0].rstrip(".")
        if _top and _top not in _seen_top:
            _seen_top.add(_top)
            app.router.add_get("/api/" + _top.lower(), _make_mock_key_handler(_top))
    app.router.add_get("/mock-data.js", _mock_data_js)
    app.router.add_get("/", static_h)
    app.router.add_get("/{path:.*}", static_h)

    async def _on_startup(_app: web.Application) -> None:
        asyncio.create_task(_self_ping())

    app.on_startup.append(_on_startup)
    return app


def main() -> None:
    logging.basicConfig(level=logging.INFO)
    web.run_app(build_app(), host="0.0.0.0", port=PORT, print=None)


if __name__ == "__main__":
    main()
